export enum OtpGenerationReasons {
    MOBILE_VERIFICATION = "MOBILE_VERIFICATION"
}

export enum OnboardingStages {
    INITIATED = "INITIATED",
    MOBILE_VERIFICATION = "MOBILE_VERIFICATION",
    EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
    USER_DETAILS_VERIFICATION = "USER_DETAILS_VERIFICATION",
    FAILED = "FAILED"
}