export const DATABASE_CONNECTION = "DATABASE_CONNECTION";
export const CUSTOMER_DATABASE = "CUSTOMER_DATABASE";
export const CUSTOMER_OTP = "CUSTOMER_OTP";
export const MENU = "MENU";
export const ORDERS = "ORDERS";